### ISSUE TITLE
Request method 'GET' not supported

### ISSUE THREAD

**Issue by jasonshark** [BandPage/js-sdk#2]
I'm trying to get data about kelly clarkson *guilty*

```
$(function() {

    var credential = {
        client_id: '5ae045d8e3c6bca7c294682592177c69',
        shared_secret: '055837ad8400b7db8ece409058e7d1e3',
        access_token: 'AAAAAgAAAAEG3Rnc70GgAAbdGdzWgdAABt0ZlCFB0AAAAAAAAAAAAAAAAU_BGYYSAAAAAQAAAADmh9fNGe9tinyTylk5r7vwHnPepA==',
        token_type: 'bearer',
        token_expiration: 1036800
    }

    bandpage.api.init(credential, {});

    var kelly_clarkson = '12334995322703872';

    bandpage.api.get({
        bid: kelly_clarkson,
        done: function(a, b){
            console.log('success!');
            console.dir(a, b);
        }, 
        fail: function(a, b){   
            console.log('failed!');
            console.dir(a, b);
        }
    });
});
```

I get an error object in the console:

```
failed!
error: "Request method 'GET' not supported"
```

How can I get data about artists based on their BID?

**Comment by jasonshark** [comment]
I guess I need to ask permission for her data first? I hit `https://api-read.bandpage.com/12334995322703872?access_token=AAAAAgAAAAEG3Rnc70GgAAbdGdzWgdAABt0ZlCFB0AAAAAAAAAAAAAAAAU_BGYYSAAAAAQAAAADmh9fNGe9tinyTylk5r7vwHnPepA==` and get an error:

```
{
error: "Permission denied",
errors: [
{
code: null,
message: "Permission denied"
}
]
}
```

@josheverett what's wrong?

**Comment by josheverett** [comment]
Hey @jasonshark, the problem here is that an administrator of Kelly Clarkson's profile would first need to authorize your application to access that artist's data. This is done via our BandPage Connect auth dialog:

https://developers.bandpage.com/sdk/connect_SDK

Once an artist has granted your application access to their data, you can freely query the band's information via our API.

**Comment by jasonshark** [comment]
So i need to generate this button on my app and have kelly clarkson's admin go to my page and click the button?

> The Bandpage Connect library should be used to render a BandPage connect button

Is there a way to send a request for permission directly to page admins? Like "Connor Leech" is asking permission to use "Kelly Clarkson"'s data [upcoming shows] for the application "ShowJunkie"

**Comment by josheverett** [comment]
> So i need to generate this button on my app and have kelly clarkson's admin go to my page and click the button?

Correct.

> Is there a way to send a request for permission directly to page admins?

No there is not. BandPage Connect works very similarly to oauth-based third party applications that you might build on top of platforms like Github, twitter, or Stripe. The developer must direct potential users to the authorization flow.

**Comment by jasonshark** [comment]
ok thank you
